export interface EmojiEntry {
  emoji: string;
  name: string;
  aliases?: string[];
}

export interface EmojiCategory {
  label: string;
  icon: string;
  emojis: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    label: "Smileys",
    icon: "😀",
    emojis: [
      { emoji: "😀", name: "grinning" },
      { emoji: "😃", name: "smiley" },
      { emoji: "😄", name: "smile" },
      { emoji: "😁", name: "grin" },
      { emoji: "😆", name: "laughing", aliases: ["satisfied"] },
      { emoji: "😅", name: "sweat_smile" },
      { emoji: "🤣", name: "rofl" },
      { emoji: "😂", name: "joy" },
      { emoji: "🙂", name: "slightly_smiling_face" },
      { emoji: "🙃", name: "upside_down_face" },
      { emoji: "😉", name: "wink" },
      { emoji: "😊", name: "blush" },
      { emoji: "😇", name: "innocent" },
      { emoji: "🥰", name: "smiling_face_with_hearts" },
      { emoji: "😍", name: "heart_eyes" },
      { emoji: "🤩", name: "star_struck" },
      { emoji: "😘", name: "kissing_heart" },
      { emoji: "😗", name: "kissing" },
      { emoji: "😚", name: "kissing_closed_eyes" },
      { emoji: "😙", name: "kissing_smiling_eyes" },
      { emoji: "🥲", name: "smiling_face_with_tear" },
      { emoji: "😋", name: "yum" },
      { emoji: "😛", name: "stuck_out_tongue" },
      { emoji: "😜", name: "stuck_out_tongue_winking_eye" },
      { emoji: "🤪", name: "zany_face" },
      { emoji: "😝", name: "stuck_out_tongue_closed_eyes" },
      { emoji: "🤑", name: "money_mouth_face" },
      { emoji: "🤗", name: "hugs" },
      { emoji: "🤭", name: "hand_over_mouth" },
      { emoji: "🤫", name: "shushing_face" },
      { emoji: "🤔", name: "thinking" },
      { emoji: "🤐", name: "zipper_mouth_face" },
      { emoji: "🤨", name: "raised_eyebrow" },
      { emoji: "😐", name: "neutral_face" },
      { emoji: "😑", name: "expressionless" },
      { emoji: "😶", name: "no_mouth" },
      { emoji: "😏", name: "smirk" },
      { emoji: "😒", name: "unamused" },
      { emoji: "🙄", name: "eye_roll", aliases: ["rolling_eyes"] },
      { emoji: "😬", name: "grimacing" },
      { emoji: "🤥", name: "lying_face" },
      { emoji: "😌", name: "relieved" },
      { emoji: "😔", name: "pensive" },
      { emoji: "😪", name: "sleepy" },
      { emoji: "🤤", name: "drooling_face" },
      { emoji: "😴", name: "sleeping" },
      { emoji: "😷", name: "mask" },
      { emoji: "🤒", name: "face_with_thermometer" },
      { emoji: "🤕", name: "face_with_head_bandage" },
      { emoji: "🤢", name: "nauseated_face" },
      { emoji: "🤮", name: "vomiting_face" },
      { emoji: "🤧", name: "sneezing_face" },
      { emoji: "🥵", name: "hot_face" },
      { emoji: "🥶", name: "cold_face" },
      { emoji: "🥴", name: "woozy_face" },
      { emoji: "😵", name: "dizzy_face" },
      { emoji: "🤯", name: "exploding_head" },
      { emoji: "🤠", name: "cowboy_hat_face" },
      { emoji: "🥳", name: "partying_face" },
      { emoji: "🥸", name: "disguised_face" },
      { emoji: "😎", name: "sunglasses" },
      { emoji: "🤓", name: "nerd_face" },
      { emoji: "🧐", name: "monocle_face" },
      { emoji: "😕", name: "confused" },
      { emoji: "😟", name: "worried" },
      { emoji: "🙁", name: "slightly_frowning_face" },
      { emoji: "☹️", name: "frowning_face" },
      { emoji: "😮", name: "open_mouth" },
      { emoji: "😯", name: "hushed" },
      { emoji: "😲", name: "astonished" },
      { emoji: "😳", name: "flushed" },
      { emoji: "🥺", name: "pleading_face" },
      { emoji: "😦", name: "frowning" },
      { emoji: "😧", name: "anguished" },
      { emoji: "😨", name: "fearful" },
      { emoji: "😰", name: "cold_sweat" },
      { emoji: "😥", name: "disappointed_relieved" },
      { emoji: "😢", name: "cry" },
      { emoji: "😭", name: "sob" },
      { emoji: "😱", name: "scream" },
      { emoji: "😖", name: "confounded" },
      { emoji: "😣", name: "persevere" },
      { emoji: "😞", name: "disappointed" },
      { emoji: "😓", name: "sweat" },
      { emoji: "😩", name: "weary" },
      { emoji: "😫", name: "tired_face" },
      { emoji: "🥱", name: "yawning_face" },
      { emoji: "😤", name: "triumph" },
      { emoji: "😡", name: "rage", aliases: ["pout"] },
      { emoji: "😠", name: "angry" },
      { emoji: "🤬", name: "cursing_face" },
      { emoji: "😈", name: "smiling_imp" },
      { emoji: "👿", name: "imp" },
      { emoji: "💀", name: "skull" },
      { emoji: "☠️", name: "skull_and_crossbones" },
      { emoji: "💩", name: "poop", aliases: ["shit"] },
      { emoji: "🤡", name: "clown_face" },
      { emoji: "👹", name: "japanese_ogre" },
      { emoji: "👺", name: "japanese_goblin" },
      { emoji: "👻", name: "ghost" },
      { emoji: "👽", name: "alien" },
      { emoji: "👾", name: "space_invader" },
      { emoji: "🤖", name: "robot" },
    ],
  },
  {
    label: "People",
    icon: "👋",
    emojis: [
      { emoji: "👋", name: "wave" },
      { emoji: "🤚", name: "raised_back_of_hand" },
      { emoji: "🖐️", name: "raised_hand_with_fingers_splayed" },
      { emoji: "✋", name: "raised_hand" },
      { emoji: "🖖", name: "vulcan_salute" },
      { emoji: "👌", name: "ok_hand" },
      { emoji: "🤌", name: "pinched_fingers" },
      { emoji: "✌️", name: "v" },
      { emoji: "🤞", name: "crossed_fingers" },
      { emoji: "🤟", name: "love_you_gesture" },
      { emoji: "🤘", name: "metal" },
      { emoji: "🤙", name: "call_me_hand" },
      { emoji: "👈", name: "point_left" },
      { emoji: "👉", name: "point_right" },
      { emoji: "👆", name: "point_up_2" },
      { emoji: "🖕", name: "fu", aliases: ["middle_finger"] },
      { emoji: "👇", name: "point_down" },
      { emoji: "☝️", name: "point_up" },
      { emoji: "👍", name: "thumbsup", aliases: ["+1"] },
      { emoji: "👎", name: "thumbsdown", aliases: ["-1"] },
      { emoji: "✊", name: "fist" },
      { emoji: "👊", name: "facepunch", aliases: ["punch"] },
      { emoji: "🤛", name: "left_facing_fist" },
      { emoji: "🤜", name: "right_facing_fist" },
      { emoji: "👏", name: "clap" },
      { emoji: "🙌", name: "raised_hands" },
      { emoji: "👐", name: "open_hands" },
      { emoji: "🤲", name: "palms_up_together" },
      { emoji: "🙏", name: "pray" },
      { emoji: "✍️", name: "writing_hand" },
      { emoji: "💅", name: "nail_care" },
      { emoji: "🤳", name: "selfie" },
      { emoji: "💪", name: "muscle" },
      { emoji: "🦾", name: "mechanical_arm" },
      { emoji: "🦵", name: "leg" },
      { emoji: "🦶", name: "foot" },
      { emoji: "👂", name: "ear" },
      { emoji: "🦻", name: "ear_with_hearing_aid" },
      { emoji: "👃", name: "nose" },
      { emoji: "👁️", name: "eye" },
      { emoji: "👀", name: "eyes" },
      { emoji: "👅", name: "tongue" },
      { emoji: "👄", name: "lips" },
      { emoji: "💋", name: "kiss" },
      { emoji: "💔", name: "broken_heart" },
      { emoji: "❤️", name: "heart", aliases: ["red_heart"] },
      { emoji: "🧡", name: "orange_heart" },
      { emoji: "💛", name: "yellow_heart" },
      { emoji: "💚", name: "green_heart" },
      { emoji: "💙", name: "blue_heart" },
      { emoji: "💜", name: "purple_heart" },
      { emoji: "🖤", name: "black_heart" },
      { emoji: "🤍", name: "white_heart" },
      { emoji: "🤎", name: "brown_heart" },
      { emoji: "💯", name: "100" },
      { emoji: "💢", name: "anger" },
      { emoji: "💥", name: "boom", aliases: ["collision"] },
      { emoji: "💫", name: "dizzy" },
      { emoji: "💦", name: "sweat_drops" },
      { emoji: "💨", name: "dash" },
      { emoji: "🕳️", name: "hole" },
      { emoji: "💬", name: "speech_balloon" },
      { emoji: "💭", name: "thought_balloon" },
    ],
  },
  {
    label: "Animals",
    icon: "🐶",
    emojis: [
      { emoji: "🐶", name: "dog" },
      { emoji: "🐱", name: "cat" },
      { emoji: "🐭", name: "mouse" },
      { emoji: "🐹", name: "hamster" },
      { emoji: "🐰", name: "rabbit" },
      { emoji: "🦊", name: "fox_face" },
      { emoji: "🐻", name: "bear" },
      { emoji: "🐼", name: "panda_face" },
      { emoji: "🐨", name: "koala" },
      { emoji: "🐯", name: "tiger" },
      { emoji: "🦁", name: "lion" },
      { emoji: "🐮", name: "cow" },
      { emoji: "🐷", name: "pig" },
      { emoji: "🐸", name: "frog" },
      { emoji: "🐵", name: "monkey_face" },
      { emoji: "🙈", name: "see_no_evil" },
      { emoji: "🙉", name: "hear_no_evil" },
      { emoji: "🙊", name: "speak_no_evil" },
      { emoji: "🐔", name: "chicken" },
      { emoji: "🐧", name: "penguin" },
      { emoji: "🐦", name: "bird" },
      { emoji: "🦆", name: "duck" },
      { emoji: "🦅", name: "eagle" },
      { emoji: "🦉", name: "owl" },
      { emoji: "🦇", name: "bat" },
      { emoji: "🐺", name: "wolf" },
      { emoji: "🐗", name: "boar" },
      { emoji: "🐴", name: "horse" },
      { emoji: "🦄", name: "unicorn" },
      { emoji: "🐝", name: "bee", aliases: ["honeybee"] },
      { emoji: "🪱", name: "worm" },
      { emoji: "🐛", name: "bug" },
      { emoji: "🦋", name: "butterfly" },
      { emoji: "🐌", name: "snail" },
      { emoji: "🐞", name: "lady_beetle", aliases: ["ladybug"] },
      { emoji: "🐜", name: "ant" },
      { emoji: "🦟", name: "mosquito" },
      { emoji: "🦗", name: "cricket" },
      { emoji: "🕷️", name: "spider" },
      { emoji: "🦂", name: "scorpion" },
      { emoji: "🐢", name: "turtle" },
      { emoji: "🐍", name: "snake" },
      { emoji: "🦎", name: "lizard" },
      { emoji: "🦖", name: "t-rex" },
      { emoji: "🦕", name: "sauropod" },
      { emoji: "🐙", name: "octopus" },
      { emoji: "🦑", name: "squid" },
      { emoji: "🦐", name: "shrimp" },
      { emoji: "🦞", name: "lobster" },
      { emoji: "🦀", name: "crab" },
      { emoji: "🐡", name: "blowfish" },
      { emoji: "🐠", name: "tropical_fish" },
      { emoji: "🐟", name: "fish" },
      { emoji: "🐬", name: "dolphin" },
      { emoji: "🐳", name: "whale" },
      { emoji: "🐋", name: "whale2" },
      { emoji: "🦈", name: "shark" },
      { emoji: "🐊", name: "crocodile" },
      { emoji: "🐅", name: "tiger2" },
      { emoji: "🐆", name: "leopard" },
      { emoji: "🦓", name: "zebra" },
      { emoji: "🦍", name: "gorilla" },
      { emoji: "🦧", name: "orangutan" },
      { emoji: "🦣", name: "mammoth" },
      { emoji: "🐘", name: "elephant" },
      { emoji: "🦛", name: "hippopotamus" },
      { emoji: "🦏", name: "rhinoceros" },
      { emoji: "🐪", name: "dromedary_camel" },
      { emoji: "🐫", name: "camel" },
      { emoji: "🦒", name: "giraffe" },
      { emoji: "🦘", name: "kangaroo" },
      { emoji: "🦬", name: "bison" },
      { emoji: "🐃", name: "water_buffalo" },
      { emoji: "🐂", name: "ox" },
      { emoji: "🐄", name: "cow2" },
      { emoji: "🐎", name: "racehorse" },
      { emoji: "🐖", name: "pig2" },
      { emoji: "🐏", name: "ram" },
      { emoji: "🐑", name: "sheep" },
      { emoji: "🦙", name: "llama" },
      { emoji: "🐐", name: "goat" },
      { emoji: "🦌", name: "deer" },
      { emoji: "🐕", name: "dog2" },
      { emoji: "🐩", name: "poodle" },
      { emoji: "🦮", name: "guide_dog" },
      { emoji: "🐈", name: "cat2" },
      { emoji: "🐓", name: "rooster" },
      { emoji: "🦃", name: "turkey" },
      { emoji: "🦤", name: "dodo" },
      { emoji: "🦚", name: "peacock" },
      { emoji: "🦜", name: "parrot" },
      { emoji: "🦢", name: "swan" },
      { emoji: "🦩", name: "flamingo" },
      { emoji: "🕊️", name: "dove" },
      { emoji: "🐇", name: "rabbit2" },
      { emoji: "🦝", name: "raccoon" },
      { emoji: "🦨", name: "skunk" },
      { emoji: "🦡", name: "badger" },
      { emoji: "🦦", name: "otter" },
      { emoji: "🦥", name: "sloth" },
      { emoji: "🐁", name: "mouse2" },
      { emoji: "🐀", name: "rat" },
      { emoji: "🐿️", name: "chipmunk" },
      { emoji: "🦔", name: "hedgehog" },
    ],
  },
  {
    label: "Food",
    icon: "🍕",
    emojis: [
      { emoji: "🍎", name: "apple" },
      { emoji: "🍊", name: "tangerine" },
      { emoji: "🍋", name: "lemon" },
      { emoji: "🍇", name: "grapes" },
      { emoji: "🍓", name: "strawberry" },
      { emoji: "🫐", name: "blueberries" },
      { emoji: "🍈", name: "melon" },
      { emoji: "🍉", name: "watermelon" },
      { emoji: "🍑", name: "peach" },
      { emoji: "🍒", name: "cherries" },
      { emoji: "🍍", name: "pineapple" },
      { emoji: "🥭", name: "mango" },
      { emoji: "🥥", name: "coconut" },
      { emoji: "🍌", name: "banana" },
      { emoji: "🍐", name: "pear" },
      { emoji: "🍏", name: "green_apple" },
      { emoji: "🫒", name: "olive" },
      { emoji: "🍅", name: "tomato" },
      { emoji: "🫑", name: "bell_pepper" },
      { emoji: "🌶️", name: "hot_pepper" },
      { emoji: "🥦", name: "broccoli" },
      { emoji: "🥬", name: "leafy_green" },
      { emoji: "🥒", name: "cucumber" },
      { emoji: "🌽", name: "corn" },
      { emoji: "🥕", name: "carrot" },
      { emoji: "🧄", name: "garlic" },
      { emoji: "🧅", name: "onion" },
      { emoji: "🥔", name: "potato" },
      { emoji: "🍠", name: "sweet_potato" },
      { emoji: "🥐", name: "croissant" },
      { emoji: "🥖", name: "french_bread" },
      { emoji: "🍞", name: "bread" },
      { emoji: "🥨", name: "pretzel" },
      { emoji: "🧀", name: "cheese" },
      { emoji: "🥚", name: "egg" },
      { emoji: "🍳", name: "fried_egg" },
      { emoji: "🥞", name: "pancakes" },
      { emoji: "🧇", name: "waffle" },
      { emoji: "🥓", name: "bacon" },
      { emoji: "🍗", name: "poultry_leg" },
      { emoji: "🍖", name: "meat_on_bone" },
      { emoji: "🌭", name: "hotdog" },
      { emoji: "🍔", name: "hamburger" },
      { emoji: "🍟", name: "fries" },
      { emoji: "🍕", name: "pizza" },
      { emoji: "🫓", name: "flatbread" },
      { emoji: "🥪", name: "sandwich" },
      { emoji: "🥙", name: "stuffed_flatbread" },
      { emoji: "🧆", name: "falafel" },
      { emoji: "🌮", name: "taco" },
      { emoji: "🌯", name: "burrito" },
      { emoji: "🫔", name: "tamale" },
      { emoji: "🥗", name: "salad" },
      { emoji: "🥘", name: "shallow_pan_of_food" },
      { emoji: "🫕", name: "fondue" },
      { emoji: "🍜", name: "ramen" },
      { emoji: "🍝", name: "spaghetti" },
      { emoji: "🍛", name: "curry" },
      { emoji: "🍲", name: "stew" },
      { emoji: "🍣", name: "sushi" },
      { emoji: "🍱", name: "bento" },
      { emoji: "🍤", name: "fried_shrimp" },
      { emoji: "🍙", name: "rice_ball" },
      { emoji: "🍚", name: "rice" },
      { emoji: "🍘", name: "rice_cracker" },
      { emoji: "🍥", name: "fish_cake" },
      { emoji: "🥟", name: "dumpling" },
      { emoji: "🥠", name: "fortune_cookie" },
      { emoji: "🥡", name: "takeout_box" },
      { emoji: "🦪", name: "oyster" },
      { emoji: "🍦", name: "icecream" },
      { emoji: "🍧", name: "shaved_ice" },
      { emoji: "🍨", name: "ice_cream" },
      { emoji: "🍩", name: "doughnut" },
      { emoji: "🍪", name: "cookie" },
      { emoji: "🎂", name: "birthday" },
      { emoji: "🍰", name: "cake" },
      { emoji: "🧁", name: "cupcake" },
      { emoji: "🥧", name: "pie" },
      { emoji: "🍫", name: "chocolate_bar" },
      { emoji: "🍬", name: "candy" },
      { emoji: "🍭", name: "lollipop" },
      { emoji: "🍮", name: "custard" },
      { emoji: "🍯", name: "honey_pot" },
      { emoji: "☕", name: "coffee" },
      { emoji: "🫖", name: "teapot" },
      { emoji: "🍵", name: "tea" },
      { emoji: "🧃", name: "beverage_box" },
      { emoji: "🥤", name: "cup_with_straw" },
      { emoji: "🧋", name: "bubble_tea" },
      { emoji: "🍺", name: "beer" },
      { emoji: "🍻", name: "beers" },
      { emoji: "🥂", name: "champagne_glass" },
      { emoji: "🍷", name: "wine_glass" },
      { emoji: "🥃", name: "tumbler_glass" },
      { emoji: "🍸", name: "cocktail" },
      { emoji: "🍹", name: "tropical_drink" },
      { emoji: "🧉", name: "mate" },
      { emoji: "🍾", name: "champagne" },
    ],
  },
  {
    label: "Travel",
    icon: "✈️",
    emojis: [
      { emoji: "🚗", name: "car", aliases: ["red_car"] },
      { emoji: "🚕", name: "taxi" },
      { emoji: "🚙", name: "blue_car" },
      { emoji: "🚌", name: "bus" },
      { emoji: "🚎", name: "trolleybus" },
      { emoji: "🏎️", name: "racing_car" },
      { emoji: "🚓", name: "police_car" },
      { emoji: "🚑", name: "ambulance" },
      { emoji: "🚒", name: "fire_engine" },
      { emoji: "🚐", name: "minibus" },
      { emoji: "🛻", name: "pickup_truck" },
      { emoji: "🚚", name: "truck" },
      { emoji: "🚛", name: "articulated_lorry" },
      { emoji: "🚜", name: "tractor" },
      { emoji: "🏍️", name: "motorcycle" },
      { emoji: "🛵", name: "motor_scooter" },
      { emoji: "🚲", name: "bike" },
      { emoji: "🛴", name: "kick_scooter" },
      { emoji: "🛹", name: "skateboard" },
      { emoji: "🛼", name: "roller_skate" },
      { emoji: "🚏", name: "busstop" },
      { emoji: "🛣️", name: "motorway" },
      { emoji: "🚦", name: "vertical_traffic_light" },
      { emoji: "🚧", name: "construction" },
      { emoji: "⛽", name: "fuelpump" },
      { emoji: "🛞", name: "wheel" },
      { emoji: "🚢", name: "ship" },
      { emoji: "⛴️", name: "ferry" },
      { emoji: "🚤", name: "speedboat" },
      { emoji: "⛵", name: "sailboat" },
      { emoji: "🛶", name: "canoe" },
      { emoji: "🚁", name: "helicopter" },
      { emoji: "✈️", name: "airplane" },
      { emoji: "🛫", name: "flight_departure" },
      { emoji: "🛬", name: "flight_arrival" },
      { emoji: "🛩️", name: "small_airplane" },
      { emoji: "🚀", name: "rocket" },
      { emoji: "🛸", name: "flying_saucer" },
      { emoji: "🪂", name: "parachute" },
      { emoji: "🛺", name: "auto_rickshaw" },
      { emoji: "🚂", name: "steam_locomotive" },
      { emoji: "🚃", name: "railway_car" },
      { emoji: "🚄", name: "bullettrain_side" },
      { emoji: "🚅", name: "bullettrain_front" },
      { emoji: "🚆", name: "train2" },
      { emoji: "🚇", name: "metro" },
      { emoji: "🚈", name: "light_rail" },
      { emoji: "🚉", name: "station" },
      { emoji: "🚊", name: "tram" },
      { emoji: "🏔️", name: "mountain_snow" },
      { emoji: "⛰️", name: "mountain" },
      { emoji: "🌋", name: "volcano" },
      { emoji: "🗻", name: "mount_fuji" },
      { emoji: "🏕️", name: "camping" },
      { emoji: "🏖️", name: "beach_umbrella" },
      { emoji: "🏜️", name: "desert" },
      { emoji: "🏝️", name: "desert_island" },
      { emoji: "🏗️", name: "building_construction" },
      { emoji: "🏛️", name: "classical_building" },
      { emoji: "🏠", name: "house" },
      { emoji: "🏡", name: "house_with_garden" },
      { emoji: "🏢", name: "office" },
      { emoji: "🏣", name: "post_office" },
      { emoji: "🏥", name: "hospital" },
      { emoji: "🏦", name: "bank" },
      { emoji: "🏨", name: "hotel" },
      { emoji: "🏪", name: "convenience_store" },
      { emoji: "🏫", name: "school" },
      { emoji: "⛪", name: "church" },
      { emoji: "🕌", name: "mosque" },
      { emoji: "🛕", name: "hindu_temple" },
      { emoji: "🕍", name: "synagogue" },
      { emoji: "⛩️", name: "shinto_shrine" },
      { emoji: "🌁", name: "foggy" },
      { emoji: "🌃", name: "night_with_stars" },
      { emoji: "🏙️", name: "cityscape" },
      { emoji: "🌄", name: "sunrise_over_mountains" },
      { emoji: "🌅", name: "sunrise" },
      { emoji: "🌆", name: "city_sunrise" },
      { emoji: "🌇", name: "city_sunset" },
      { emoji: "🌉", name: "bridge_at_night" },
      { emoji: "🗺️", name: "world_map" },
      { emoji: "🗼", name: "tokyo_tower" },
      { emoji: "🗽", name: "statue_of_liberty" },
      { emoji: "🏰", name: "european_castle" },
      { emoji: "🏯", name: "japanese_castle" },
    ],
  },
  {
    label: "Activities",
    icon: "⚽",
    emojis: [
      { emoji: "⚽", name: "soccer" },
      { emoji: "🏀", name: "basketball" },
      { emoji: "🏈", name: "football" },
      { emoji: "⚾", name: "baseball" },
      { emoji: "🥎", name: "softball" },
      { emoji: "🎾", name: "tennis" },
      { emoji: "🏐", name: "volleyball" },
      { emoji: "🏉", name: "rugby_football" },
      { emoji: "🎱", name: "8ball" },
      { emoji: "🏓", name: "ping_pong" },
      { emoji: "🏸", name: "badminton" },
      { emoji: "🥊", name: "boxing_glove" },
      { emoji: "🥋", name: "martial_arts_uniform" },
      { emoji: "🥅", name: "goal_net" },
      { emoji: "⛳", name: "golf" },
      { emoji: "🏹", name: "bow_and_arrow" },
      { emoji: "🎣", name: "fishing_pole_and_fish" },
      { emoji: "🤿", name: "diving_mask" },
      { emoji: "🎿", name: "ski" },
      { emoji: "🛷", name: "sled" },
      { emoji: "🥌", name: "curling_stone" },
      { emoji: "🎯", name: "dart" },
      { emoji: "🪃", name: "boomerang" },
      { emoji: "🏋️", name: "weight_lifting" },
      { emoji: "🤼", name: "wrestlers" },
      { emoji: "🤸", name: "cartwheel" },
      { emoji: "🏊", name: "swimmer" },
      { emoji: "🚴", name: "bicyclist" },
      { emoji: "🏇", name: "horse_racing" },
      { emoji: "🧗", name: "climbing" },
      { emoji: "🏄", name: "surfer" },
      { emoji: "🤾", name: "handball_person" },
      { emoji: "🏌️", name: "golfing" },
      { emoji: "🧘", name: "person_in_lotus_position" },
      { emoji: "🎽", name: "running_shirt_with_sash" },
      { emoji: "🎮", name: "video_game" },
      { emoji: "🕹️", name: "joystick" },
      { emoji: "🎲", name: "game_die" },
      { emoji: "♟️", name: "chess_pawn" },
      { emoji: "🎭", name: "performing_arts" },
      { emoji: "🎨", name: "art" },
      { emoji: "🎬", name: "clapper" },
      { emoji: "🎤", name: "microphone" },
      { emoji: "🎧", name: "headphones" },
      { emoji: "🎼", name: "musical_score" },
      { emoji: "🎹", name: "musical_keyboard" },
      { emoji: "🥁", name: "drum" },
      { emoji: "🪘", name: "long_drum" },
      { emoji: "🎷", name: "saxophone" },
      { emoji: "🎺", name: "trumpet" },
      { emoji: "🎸", name: "guitar" },
      { emoji: "🪕", name: "banjo" },
      { emoji: "🎻", name: "violin" },
      { emoji: "🪗", name: "accordion" },
      { emoji: "🎙️", name: "studio_microphone" },
      { emoji: "🎚️", name: "level_slider" },
      { emoji: "🎛️", name: "control_knobs" },
      { emoji: "📻", name: "radio" },
      { emoji: "🎞️", name: "film_frames" },
      { emoji: "📽️", name: "film_projector" },
      { emoji: "🎥", name: "movie_camera" },
      { emoji: "📺", name: "tv" },
      { emoji: "🎡", name: "ferris_wheel" },
      { emoji: "🎢", name: "roller_coaster" },
      { emoji: "🎠", name: "carousel_horse" },
      { emoji: "🎪", name: "circus_tent" },
      { emoji: "🤹", name: "juggling_person" },
      { emoji: "🎉", name: "tada" },
      { emoji: "🎊", name: "confetti_ball" },
      { emoji: "🎈", name: "balloon" },
      { emoji: "🎀", name: "ribbon" },
      { emoji: "🎁", name: "gift" },
      { emoji: "🏆", name: "trophy" },
      { emoji: "🥇", name: "first_place_medal" },
      { emoji: "🥈", name: "second_place_medal" },
      { emoji: "🥉", name: "third_place_medal" },
      { emoji: "🏅", name: "sports_medal" },
      { emoji: "🎖️", name: "military_medal" },
      { emoji: "🎗️", name: "reminder_ribbon" },
    ],
  },
  {
    label: "Objects",
    icon: "💡",
    emojis: [
      { emoji: "💡", name: "bulb" },
      { emoji: "🔦", name: "flashlight" },
      { emoji: "🕯️", name: "candle" },
      { emoji: "💰", name: "moneybag" },
      { emoji: "💳", name: "credit_card" },
      { emoji: "💎", name: "gem" },
      { emoji: "⚖️", name: "balance_scale" },
      { emoji: "🔧", name: "wrench" },
      { emoji: "🔨", name: "hammer" },
      { emoji: "⚒️", name: "hammer_and_pick" },
      { emoji: "🛠️", name: "hammer_and_wrench" },
      { emoji: "⛏️", name: "pick" },
      { emoji: "🔩", name: "nut_and_bolt" },
      { emoji: "🪛", name: "screwdriver" },
      { emoji: "🔫", name: "gun" },
      { emoji: "🪃", name: "boomerang" },
      { emoji: "🛡️", name: "shield" },
      { emoji: "🪚", name: "carpentry_saw" },
      { emoji: "🔪", name: "knife" },
      { emoji: "🗡️", name: "dagger" },
      { emoji: "⚔️", name: "crossed_swords" },
      { emoji: "🧲", name: "magnet" },
      { emoji: "🪜", name: "ladder" },
      { emoji: "🧰", name: "toolbox" },
      { emoji: "🔭", name: "telescope" },
      { emoji: "🔬", name: "microscope" },
      { emoji: "💊", name: "pill" },
      { emoji: "🩺", name: "stethoscope" },
      { emoji: "🩹", name: "adhesive_bandage" },
      { emoji: "🧬", name: "dna" },
      { emoji: "🔑", name: "key" },
      { emoji: "🗝️", name: "old_key" },
      { emoji: "🪝", name: "hook" },
      { emoji: "🔓", name: "unlock" },
      { emoji: "🔒", name: "lock" },
      { emoji: "🪤", name: "mouse_trap" },
      { emoji: "🧸", name: "teddy_bear" },
      { emoji: "🪆", name: "nesting_dolls" },
      { emoji: "🎎", name: "dolls" },
      { emoji: "🪄", name: "magic_wand" },
      { emoji: "📱", name: "iphone" },
      { emoji: "💻", name: "computer" },
      { emoji: "⌨️", name: "keyboard" },
      { emoji: "🖥️", name: "desktop_computer" },
      { emoji: "🖨️", name: "printer" },
      { emoji: "🖱️", name: "computer_mouse" },
      { emoji: "💾", name: "floppy_disk" },
      { emoji: "💿", name: "cd" },
      { emoji: "📀", name: "dvd" },
      { emoji: "📷", name: "camera" },
      { emoji: "📸", name: "camera_flash" },
      { emoji: "📹", name: "video_camera" },
      { emoji: "📞", name: "telephone_receiver" },
      { emoji: "☎️", name: "phone", aliases: ["telephone"] },
      { emoji: "📟", name: "pager" },
      { emoji: "📠", name: "fax" },
      { emoji: "🔋", name: "battery" },
      { emoji: "🔌", name: "electric_plug" },
      { emoji: "💡", name: "bulb" },
      { emoji: "🔦", name: "flashlight" },
      { emoji: "📚", name: "books" },
      { emoji: "📖", name: "book", aliases: ["open_book"] },
      { emoji: "📝", name: "memo", aliases: ["pencil"] },
      { emoji: "✏️", name: "pencil2" },
      { emoji: "🖊️", name: "pen" },
      { emoji: "🖋️", name: "fountain_pen" },
      { emoji: "📌", name: "pushpin" },
      { emoji: "📍", name: "round_pushpin" },
      { emoji: "🗂️", name: "card_index_dividers" },
      { emoji: "📁", name: "file_folder" },
      { emoji: "📂", name: "open_file_folder" },
      { emoji: "🗃️", name: "card_file_box" },
      { emoji: "🗄️", name: "file_cabinet" },
      { emoji: "🗑️", name: "wastebasket" },
      { emoji: "📦", name: "package" },
      { emoji: "📫", name: "mailbox" },
      { emoji: "📬", name: "mailbox_with_mail" },
      { emoji: "📭", name: "mailbox_with_no_mail" },
      { emoji: "📮", name: "postbox" },
      { emoji: "🗳️", name: "ballot_box" },
      { emoji: "✂️", name: "scissors" },
      { emoji: "🖇️", name: "paperclip" },
      { emoji: "📎", name: "paperclips" },
      { emoji: "📐", name: "triangular_ruler" },
      { emoji: "📏", name: "straight_ruler" },
    ],
  },
  {
    label: "Symbols",
    icon: "❤️",
    emojis: [
      { emoji: "❤️", name: "heart" },
      { emoji: "🧡", name: "orange_heart" },
      { emoji: "💛", name: "yellow_heart" },
      { emoji: "💚", name: "green_heart" },
      { emoji: "💙", name: "blue_heart" },
      { emoji: "💜", name: "purple_heart" },
      { emoji: "🖤", name: "black_heart" },
      { emoji: "🤍", name: "white_heart" },
      { emoji: "🤎", name: "brown_heart" },
      { emoji: "💔", name: "broken_heart" },
      { emoji: "❣️", name: "heavy_heart_exclamation" },
      { emoji: "💕", name: "two_hearts" },
      { emoji: "💞", name: "revolving_hearts" },
      { emoji: "💓", name: "heartbeat" },
      { emoji: "💗", name: "heartpulse" },
      { emoji: "💖", name: "sparkling_heart" },
      { emoji: "💘", name: "cupid" },
      { emoji: "💝", name: "gift_heart" },
      { emoji: "💟", name: "heart_decoration" },
      { emoji: "☮️", name: "peace_symbol" },
      { emoji: "✝️", name: "latin_cross" },
      { emoji: "☯️", name: "yin_yang" },
      { emoji: "✡️", name: "star_of_david" },
      { emoji: "🔯", name: "six_pointed_star" },
      { emoji: "🕉️", name: "om" },
      { emoji: "☪️", name: "star_and_crescent" },
      { emoji: "☸️", name: "wheel_of_dharma" },
      { emoji: "🛐", name: "place_of_worship" },
      { emoji: "♻️", name: "recycle" },
      { emoji: "🔱", name: "trident" },
      { emoji: "📛", name: "name_badge" },
      { emoji: "🔰", name: "beginner" },
      { emoji: "⭕", name: "o" },
      { emoji: "✅", name: "white_check_mark" },
      { emoji: "☑️", name: "ballot_box_with_check" },
      { emoji: "✔️", name: "heavy_check_mark" },
      { emoji: "❌", name: "x" },
      { emoji: "❎", name: "negative_squared_cross_mark" },
      { emoji: "➕", name: "heavy_plus_sign" },
      { emoji: "➖", name: "heavy_minus_sign" },
      { emoji: "➗", name: "heavy_division_sign" },
      { emoji: "✖️", name: "heavy_multiplication_x" },
      { emoji: "♾️", name: "infinity" },
      { emoji: "💲", name: "heavy_dollar_sign" },
      { emoji: "💱", name: "currency_exchange" },
      { emoji: "™️", name: "tm" },
      { emoji: "©️", name: "copyright" },
      { emoji: "®️", name: "registered" },
      { emoji: "〰️", name: "wavy_dash" },
      { emoji: "➰", name: "curly_loop" },
      { emoji: "➿", name: "loop" },
      { emoji: "🔚", name: "end" },
      { emoji: "🔙", name: "back" },
      { emoji: "🔛", name: "on" },
      { emoji: "🔜", name: "soon" },
      { emoji: "🔝", name: "top" },
      { emoji: "🔴", name: "red_circle" },
      { emoji: "🟠", name: "orange_circle" },
      { emoji: "🟡", name: "yellow_circle" },
      { emoji: "🟢", name: "green_circle" },
      { emoji: "🔵", name: "blue_circle" },
      { emoji: "🟣", name: "purple_circle" },
      { emoji: "⚫", name: "black_circle" },
      { emoji: "⚪", name: "white_circle" },
      { emoji: "🟤", name: "brown_circle" },
      { emoji: "🔷", name: "large_blue_diamond" },
      { emoji: "🔶", name: "large_orange_diamond" },
      { emoji: "🔸", name: "small_orange_diamond" },
      { emoji: "🔹", name: "small_blue_diamond" },
      { emoji: "🔺", name: "small_red_triangle" },
      { emoji: "🔻", name: "small_red_triangle_down" },
      { emoji: "💠", name: "diamond_shape_with_a_dot_inside" },
      { emoji: "🔘", name: "radio_button" },
      { emoji: "🔲", name: "black_square_button" },
      { emoji: "🔳", name: "white_square_button" },
      { emoji: "⬛", name: "black_large_square" },
      { emoji: "⬜", name: "white_large_square" },
      { emoji: "◼️", name: "black_medium_square" },
      { emoji: "◻️", name: "white_medium_square" },
      { emoji: "◾", name: "black_medium_small_square" },
      { emoji: "◽", name: "white_medium_small_square" },
      { emoji: "▪️", name: "black_small_square" },
      { emoji: "▫️", name: "white_small_square" },
      { emoji: "🌐", name: "globe_with_meridians" },
      { emoji: "🗺️", name: "world_map" },
      { emoji: "🧭", name: "compass" },
      { emoji: "🌍", name: "earth_africa" },
      { emoji: "🌎", name: "earth_americas" },
      { emoji: "🌏", name: "earth_asia" },
      { emoji: "☀️", name: "sunny" },
      { emoji: "🌤️", name: "partly_sunny" },
      { emoji: "⛅", name: "sun_behind_cloud" },
      { emoji: "🌦️", name: "sun_behind_rain_cloud" },
      { emoji: "🌧️", name: "cloud_with_rain" },
      { emoji: "⛈️", name: "cloud_with_lightning_and_rain" },
      { emoji: "🌩️", name: "cloud_with_lightning" },
      { emoji: "🌨️", name: "cloud_with_snow" },
      { emoji: "❄️", name: "snowflake" },
      { emoji: "⛄", name: "snowman" },
      { emoji: "🌬️", name: "wind_face" },
      { emoji: "💨", name: "dash" },
      { emoji: "🌊", name: "ocean" },
      { emoji: "🌀", name: "cyclone" },
      { emoji: "🌈", name: "rainbow" },
      { emoji: "⚡", name: "zap" },
      { emoji: "🔥", name: "fire" },
      { emoji: "💧", name: "droplet" },
      { emoji: "🌱", name: "seedling" },
      { emoji: "🌿", name: "herb" },
      { emoji: "🍀", name: "four_leaf_clover" },
      { emoji: "🌸", name: "cherry_blossom" },
      { emoji: "🌺", name: "hibiscus" },
      { emoji: "🌻", name: "sunflower" },
      { emoji: "🌹", name: "rose" },
      { emoji: "🥀", name: "wilted_flower" },
      { emoji: "🌷", name: "tulip" },
      { emoji: "🌼", name: "blossom" },
      { emoji: "⭐", name: "star" },
      { emoji: "🌟", name: "star2" },
      { emoji: "✨", name: "sparkles" },
      { emoji: "🌙", name: "crescent_moon" },
      { emoji: "🌛", name: "first_quarter_moon_with_face" },
      { emoji: "🌝", name: "full_moon_with_face" },
      { emoji: "🌞", name: "sun_with_face" },
      { emoji: "🪐", name: "ringed_planet" },
      { emoji: "🌕", name: "full_moon" },
      { emoji: "🌖", name: "waning_gibbous_moon" },
      { emoji: "🌗", name: "last_quarter_moon" },
      { emoji: "🌘", name: "waning_crescent_moon" },
      { emoji: "🌑", name: "new_moon" },
      { emoji: "🌒", name: "waxing_crescent_moon" },
      { emoji: "🌓", name: "first_quarter_moon" },
      { emoji: "🌔", name: "waxing_gibbous_moon" },
    ],
  },
];

/** Flat lookup map: name/alias → emoji character */
const NAME_TO_EMOJI: Map<string, string> = new Map();

for (const cat of EMOJI_CATEGORIES) {
  for (const entry of cat.emojis) {
    NAME_TO_EMOJI.set(entry.name, entry.emoji);
    for (const alias of entry.aliases ?? []) {
      NAME_TO_EMOJI.set(alias, entry.emoji);
    }
  }
}

/** Replace :name: patterns in text with actual emoji characters. */
export function parseEmoji(text: string): string {
  return text.replace(/:([a-zA-Z0-9_+\-]+):/g, (match, name) => {
    return NAME_TO_EMOJI.get(name) ?? match;
  });
}

/** Search emojis by name prefix, returning up to `limit` matches. */
export function searchEmoji(query: string, limit = 20): EmojiEntry[] {
  const q = query.toLowerCase();
  const results: EmojiEntry[] = [];
  for (const cat of EMOJI_CATEGORIES) {
    for (const entry of cat.emojis) {
      if (entry.name.includes(q) || entry.aliases?.some((a) => a.includes(q))) {
        results.push(entry);
        if (results.length >= limit) return results;
      }
    }
  }
  return results;
}
